export const UP_OPERATION = 'UP_OPERATION';
export const CHANGE_DIRECTORY_OPERATION = 'CHANGE_DIRECTORY_OPERATION';
export const LIST_OPERATION = 'LIST_OPERATION';

export const PRINT_OPERATION = 'cat';
export const CREATE_OPERATION = 'add';
export const RENAME_OPERATION = 'rn';
export const COPY_OPERATION = 'cp';
export const MOVE_OPERATION = 'mv';
export const DELETE_OPERATION = 'rm';

export const SYSTEM_INFO_OPERATION = 'SYSTEM_INFO_OPERATION';

export const HASH_CALCULATION_OPERATION = 'HASH_CALCULATION_OPERATION';

export const COMPRESS_OPERATION = 'COMPRESS_OPERATION';
export const DECOMPRESS_OPERATION = 'DECOMPRESS_OPERATION';

export const EXIT_OPERATION = '.exit';
export const INVALID_OPERATION = 'INVALID_OPERATION';
